In [1]:
import numpy as np

In [2]:
ar1 = np.array([0,1,2,3])
ar2 = np.array([[0,3,5],[2,8,7]])

In [3]:
ar1

array([0, 1, 2, 3])

In [4]:
ar2

array([[0, 3, 5],
       [2, 8, 7]])

In [5]:
ar2.shape

(2, 3)

In [6]:
len(ar2)

2

In [7]:
ar2.ndim

2

In [8]:
ar3 = np.arange(12)
ar3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [10]:
ar4 = np.arange(3,10,3)
ar4

array([3, 6, 9])

In [18]:
ar5 = np.linspace(1,10,10)
ar5

array([  1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.])

In [19]:
np.random.seed(100)
ar11 = np.random.rand(3)

In [20]:
ar11

array([ 0.54340494,  0.27836939,  0.42451759])

In [21]:
np.zeros((4,2))

array([[ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.]])

In [22]:
np.ones((3,2))

array([[ 1.,  1.],
       [ 1.,  1.],
       [ 1.,  1.]])

In [23]:
np.tile(np.array([[1,2],[6,7]]),3)

array([[1, 2, 1, 2, 1, 2],
       [6, 7, 6, 7, 6, 7]])

In [24]:
np.tile(np.array([[1,2],[6,7]]),(3,2)) #repeat array in 2D

array([[1, 2, 1, 2],
       [6, 7, 6, 7],
       [1, 2, 1, 2],
       [6, 7, 6, 7],
       [1, 2, 1, 2],
       [6, 7, 6, 7]])

In [25]:
sar=np.array(['Goodbye','Welcome','Tata','Goodnight']); 
sar.dtype

dtype('S9')

In [26]:
ar = np.arange(5);
print ar;ar[0],ar[1],ar[-1]

[0 1 2 3 4]


(0, 1, 4)

In [27]:
np.random.seed(10);
ar = np.random.random_integers(0,25,10);
ar

array([ 9,  4, 15,  0, 17, 25, 16, 17,  8,  9])

In [28]:
evenmask = (ar % 2 ==0);
evenmask

array([False,  True, False,  True, False, False,  True, False,  True, False], dtype=bool)

In [29]:
ar[evenmask]

array([ 4,  0, 16,  8])

In [30]:
ar=np.array(['Hungary','Nigeria', 
                       'Guatemala','','Poland',
                       '','Japan']); ar

array(['Hungary', 'Nigeria', 'Guatemala', '', 'Poland', '', 'Japan'], 
      dtype='|S9')

In [31]:
ar[ar=='']='USA';ar

array(['Hungary', 'Nigeria', 'Guatemala', 'USA', 'Poland', 'USA', 'Japan'], 
      dtype='|S9')

In [32]:
ar = 11*np.arange(0,10);
ar

array([ 0, 11, 22, 33, 44, 55, 66, 77, 88, 99])

In [34]:
ar[[1,3,4]]

array([11, 33, 44])

In [35]:
import pandas as pd

In [36]:
ser = pd.Series(np.random.rand(7));
ser

0    0.169111
1    0.088340
2    0.685360
3    0.953393
4    0.003948
5    0.512192
6    0.812621
dtype: float64

In [37]:
import calendar as cal

In [38]:
monthNames=[cal.month_name[i] for i in np.arange(1,6)]
monthNames

['January', 'February', 'March', 'April', 'May']

In [39]:
months=pd.Series(np.arange(1,6),index=monthNames); months

January     1
February    2
March       3
April       4
May         5
dtype: int64

In [40]:
currDict={'US' : 'dollar', 'UK' : 'pound', 
                    'Germany': 'euro', 'Mexico':'peso',
                    'Nigeria':'naira',
                    'China':'yuan', 'Japan':'yen'};
currDict

{'China': 'yuan',
 'Germany': 'euro',
 'Japan': 'yen',
 'Mexico': 'peso',
 'Nigeria': 'naira',
 'UK': 'pound',
 'US': 'dollar'}

In [41]:
pd.Series(currDict)

China        yuan
Germany      euro
Japan         yen
Mexico       peso
Nigeria     naira
UK          pound
US         dollar
dtype: object

In [42]:
stockPrices = {'GOOG':1180.97,'FB':62.57, 
                         'TWTR': 64.50, 'AMZN':358.69,
                         'AAPL':500.6}
stockPrices.keys()

['GOOG', 'TWTR', 'FB', 'AAPL', 'AMZN']

In [50]:
stockPriceSeries=pd.Series(stockPrices,index=stockPrices.keys(),name='stockPrices');
stockPriceSeries

GOOG    1180.97
TWTR      64.50
FB        62.57
AAPL     500.60
AMZN     358.69
Name: stockPrices, dtype: float64

In [45]:
dogSeries=pd.Series('chihuahua', 
                   index=['breed','countryOfOrigin',
                   'name', 'gender'])
dogSeries

breed              chihuahua
countryOfOrigin    chihuahua
name               chihuahua
gender             chihuahua
dtype: object

In [46]:
currDict['China']

'yuan'

In [51]:
stockPriceSeries[stockPriceSeries>100]

GOOG    1180.97
AAPL     500.60
AMZN     358.69
Name: stockPrices, dtype: float64

In [52]:
stockPriceSeries['GOOG']

1180.97

In [54]:
stockPriceSeries[:4]

GOOG    1180.97
TWTR      64.50
FB        62.57
AAPL     500.60
Name: stockPrices, dtype: float64

In [55]:
np.mean(stockPriceSeries)

433.466

In [56]:
np.std(stockPriceSeries)

410.50223047384287

In [57]:
ser

0    0.169111
1    0.088340
2    0.685360
3    0.953393
4    0.003948
5    0.512192
6    0.812621
dtype: float64

In [58]:
ser*ser

0    0.028598
1    0.007804
2    0.469718
3    0.908959
4    0.000016
5    0.262341
6    0.660353
dtype: float64

In [59]:
np.sqrt(ser*ser)

0    0.169111
1    0.088340
2    0.685360
3    0.953393
4    0.003948
5    0.512192
6    0.812621
dtype: float64

In [60]:
ser[1:]

1    0.088340
2    0.685360
3    0.953393
4    0.003948
5    0.512192
6    0.812621
dtype: float64

In [61]:
ser[:-2]

0    0.169111
1    0.088340
2    0.685360
3    0.953393
4    0.003948
dtype: float64

In [64]:
(ser[1:]+ser[:-2])/2

0         NaN
1    0.088340
2    0.685360
3    0.953393
4    0.003948
5         NaN
6         NaN
dtype: float64

In [63]:
0.088340*2

0.17668

In [65]:
ser2=ser[1:]+ser[:-2]

In [66]:
ser2

0         NaN
1    0.176680
2    1.370720
3    1.906787
4    0.007897
5         NaN
6         NaN
dtype: float64

In [73]:
ser2[np.isnan(ser2)]=0;
ser2

0    0.000000
1    0.176680
2    1.370720
3    1.906787
4    0.007897
5    0.000000
6    0.000000
dtype: float64

In [74]:
stockSummaries={
'AMZN': pd.Series([346.15,0.59,459,0.52,589.8,158.88], 
        index=['Closing price','EPS',
                'Shares Outstanding(M)',
                'Beta', 'P/E','Market Cap(B)']),
'GOOG': pd.Series([1133.43,36.05,335.83,0.87,31.44,380.64],
        index=['Closing price','EPS','Shares Outstanding(M)',
               'Beta','P/E','Market Cap(B)']),
'FB': pd.Series([61.48,0.59,2450,104.93,150.92], 
      index=['Closing price','EPS','Shares Outstanding(M)',
             'P/E', 'Market Cap(B)']),
'YHOO': pd.Series([34.90,1.27,1010,27.48,0.66,35.36],
        index=['Closing price','EPS','Shares Outstanding(M)',
               'P/E','Beta', 'Market Cap(B)']),
'TWTR':pd.Series([65.25,-0.3,555.2,36.23],
       index=['Closing price','EPS','Shares Outstanding(M)',
              'Market Cap(B)']), 
'AAPL':pd.Series([501.53,40.32,892.45,12.44,447.59,0.84],
       index=['Closing price','EPS','Shares Outstanding(M)','P/E',
              'Market Cap(B)','Beta'])}

In [75]:
stockDF=pd.DataFrame(stockSummaries);
stockDF

AAPL    AMZN       FB     GOOG    TWTR     YHOO
Beta                     0.84    0.52      NaN     0.87     NaN     0.66
Closing price          501.53  346.15    61.48  1133.43   65.25    34.90
EPS                     40.32    0.59     0.59    36.05   -0.30     1.27
Market Cap(B)          447.59  158.88   150.92   380.64   36.23    35.36
P/E                     12.44  589.80   104.93    31.44     NaN    27.48
Shares Outstanding(M)  892.45  459.00  2450.00   335.83  555.20  1010.00

In [76]:
stockDF['AAPL']

Beta                       0.84
Closing price            501.53
EPS                       40.32
Market Cap(B)            447.59
P/E                       12.44
Shares Outstanding(M)    892.45
Name: AAPL, dtype: float64

In [77]:
stockDF.index

Index([u'Beta', u'Closing price', u'EPS', u'Market Cap(B)', u'P/E',
       u'Shares Outstanding(M)'],
      dtype='object')

In [80]:
stockDF.columns

Index([u'AAPL', u'AMZN', u'FB', u'GOOG', u'TWTR', u'YHOO'], dtype='object')

In [82]:
memberDF=pd.DataFrame({'Name':['Sanjeev', 'Yingluck', 'Emeka', 'Amy']})

In [83]:
memberDF

Name
0   Sanjeev
1  Yingluck
2     Emeka
3       Amy

In [84]:
memberDF['Height']=60;memberDF

Name  Height
0   Sanjeev      60
1  Yingluck      60
2     Emeka      60
3       Amy      60

In [86]:
memberDF['Age']=[37,45,28,67];
memberDF['Weight']=[162.4,137.8,153.2,101.3]
memberDF

Name  Height  Age  Weight
0   Sanjeev      60   37   162.4
1  Yingluck      60   45   137.8
2     Emeka      60   28   153.2
3       Amy      60   67   101.3

In [87]:
del memberDF['Height'];
memberDF

Name  Age  Weight
0   Sanjeev   37   162.4
1  Yingluck   45   137.8
2     Emeka   28   153.2
3       Amy   67   101.3

In [88]:
memberDF['BloodType']='O';
memberDF

Name  Age  Weight BloodType
0   Sanjeev   37   162.4         O
1  Yingluck   45   137.8         O
2     Emeka   28   153.2         O
3       Amy   67   101.3         O

In [89]:
bloodType=memberDF.pop('BloodType');
bloodType

0    O
1    O
2    O
3    O
Name: BloodType, dtype: object

In [91]:
memberDF.insert(2,'isSenior', memberDF['Age']>60);
memberDF

Name  Age isSenior  Weight
0   Sanjeev   37    False   162.4
1  Yingluck   45    False   137.8
2     Emeka   28    False   153.2
3       Amy   67     True   101.3

In [92]:
ore1DF=pd.DataFrame(np.array([[20,35,25,20],
                                       [11,28,32,29]]),
                              columns=['iron','magnesium',
                                       'copper','silver']);
ore1DF

iron  magnesium  copper  silver
0    20         35      25      20
1    11         28      32      29

In [93]:
ore2DF=pd.DataFrame(np.array([[14,34,26,26],
                                   [33,19,25,23]]),
                             columns=['iron','magnesium',
                                     'gold','silver']);
ore2DF

iron  magnesium  gold  silver
0    14         34    26      26
1    33         19    25      23

In [94]:
ore1DF+ore2DF

copper  gold  iron  magnesium  silver
0     NaN   NaN    34         69      46
1     NaN   NaN    44         47      52

In [95]:
np.sqrt(ore1DF)

iron  magnesium    copper    silver
0  4.472136   5.916080  5.000000  4.472136
1  3.316625   5.291503  5.656854  5.385165