In [2]:
%pylab inline
import numpy as np

Populating the interactive namespace from numpy and matplotlib


In [2]:
for i in range(5):
    if i == 3:
        print('Three')
        continue
    print(i)

0
1
2
Three
4


In [3]:
for i in range(9):
    print(i)
    if i == 3:
        print('Three')
        break

0
1
2
3
Three


In [4]:
for i in range(5):
    print(i)
else:
    print(i, 'in else clause')

0
1
2
3
4
(4, 'in else clause')


In [5]:
import math
dir(math)

['__doc__',
 '__file__',
 '__name__',
 '__package__',
 'acos',
 'acosh',
 'asin',
 'asinh',
 'atan',
 'atan2',
 'atanh',
 'ceil',
 'copysign',
 'cos',
 'cosh',
 'degrees',
 'e',
 'erf',
 'erfc',
 'exp',
 'expm1',
 'fabs',
 'factorial',
 'floor',
 'fmod',
 'frexp',
 'fsum',
 'gamma',
 'hypot',
 'isinf',
 'isnan',
 'ldexp',
 'lgamma',
 'log',
 'log10',
 'log1p',
 'modf',
 'pi',
 'pow',
 'radians',
 'sin',
 'sinh',
 'sqrt',
 'tan',
 'tanh',
 'trunc']

In [7]:
math.pow(2,3)

8.0

In [12]:
import numpy as np
def numpysum(n):
    a = np.arange(n) ** 2
    b = np.arange(n) ** 3
    c = a + b
    return c
numpysum(3)

array([ 0,  2, 12])

In [4]:
%run ch1_numpy_beginner.py 1000000

The last 2 elements of the sum [999995000007999996, 999998000001000000]
PythonSum elapsed time in microseconds 431010
The last 2 elements of the sum [999995000008000004 999998000000999937]
NumPySum elapsed time in microseconds 55903


In [5]:
%logstart

Activating auto-logging. Current session state plus future input saved.
Filename       : ipython_log.py
Mode           : rotate
Output logging : False
Raw input log  : False
Timestamping   : False
State          : active


In [8]:
ls -al

total 1432
drwxr-xr-x   8 fanchang  5000     272 Feb 13 22:13 ./
drwxr-xr-x+ 47 fanchang  5000    1598 Feb 13 21:20 ../
drwxr-xr-x   4 fanchang  5000     136 Feb 13 21:45 .ipynb_checkpoints/
-rw-r--r--   1 fanchang  5000    1225 Feb 13 22:06 ch1_numpy_beginner.py
-rw-r--r--   1 fanchang  5000     373 Feb 13 22:13 ipython_log.py
-rw-r--r--   1 fanchang  5000  712080 Feb 13 21:53 ipython_study_20160213.ipynb
-rw-r--r--   1 fanchang  5000     727 Feb 13 21:27 lorenz.py
-rw-r--r--   1 fanchang  5000    5142 Feb 13 22:13 numpy_study_20160213.ipynb


In [4]:
%run -i ch1_numpy_beginner.py 1000

The last 2 elements of the sum [995007996, 998001000]
PythonSum elapsed time in microseconds 704
The last 2 elements of the sum [995007996 998001000]
NumPySum elapsed time in microseconds 95


In [10]:
%hist

%run ch1_numpy_beginner.py 1000
%run ch1_numpy_beginner.py 1000000
%run ch1_numpy_beginner.py 100000000
%run ch1_numpy_beginner.py 1000000
%logstart
ls
ls -l
ls -al
%run -i ch1_numpy_beginner.py 1000
%hist


In [5]:
a=arange(5)
a.dtype

dtype('int64')

In [6]:
a

array([0, 1, 2, 3, 4])

In [7]:
a.shape

(5,)

In [13]:
m=np.array([np.arange(2),np.arange(3)])
print m
print m.shape

[array([0, 1]) array([0, 1, 2])]
(2,)


In [16]:
a=array([[1,2],[3,4]])
a

array([[1, 2],
       [3, 4]])

In [17]:
a[0,0]

1

In [18]:
finfo(float16)

finfo(resolution=0.0010004, min=-6.55040e+04, max=6.55040e+04, dtype=float16)

In [19]:
finfo(float32)

finfo(resolution=1e-06, min=-3.4028235e+38, max=3.4028235e+38, dtype=float32)

In [22]:
complex(1.2,1.0)

(1.2+1j)

In [23]:
t = dtype([('name', str_, 40), ('numitems', int32), ('price', float32)])
t

dtype([('name', 'S40'), ('numitems', '<i4'), ('price', '<f4')])

In [24]:
a=arange(9)
a[3:7]

array([3, 4, 5, 6])

In [25]:
a[:7:2]

array([0, 2, 4, 6])

In [26]:
a[::-1]

array([8, 7, 6, 5, 4, 3, 2, 1, 0])

In [27]:
b=arange(24).reshape(2,3,4)
b

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [28]:
b.shape 

(2, 3, 4)

In [29]:
b.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [30]:
b.shape=(6,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [31]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [32]:
b.resize((2,12))

In [33]:
b

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

In [34]:
a=arange(9).reshape(3,3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [35]:
b=2*a
b

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

In [40]:
vstack((a,b))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

In [41]:
concatenate((a,b),axis=1)

array([[ 0,  1,  2,  0,  2,  4],
       [ 3,  4,  5,  6,  8, 10],
       [ 6,  7,  8, 12, 14, 16]])

In [42]:
concatenate((a,b),axis=0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

In [43]:
c=dstack((a,b))
print c
print c.shape

[[[ 0  0]
  [ 1  2]
  [ 2  4]]

 [[ 3  6]
  [ 4  8]
  [ 5 10]]

 [[ 6 12]
  [ 7 14]
  [ 8 16]]]
(3, 3, 2)


In [44]:
print a
hsplit(a,3)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


[array([[0],
        [3],
        [6]]), array([[1],
        [4],
        [7]]), array([[2],
        [5],
        [8]])]

In [45]:
vsplit(a,3)

[array([[0, 1, 2]]), array([[3, 4, 5]]), array([[6, 7, 8]])]

In [46]:
split(a,3,axis=1)

[array([[0],
        [3],
        [6]]), array([[1],
        [4],
        [7]]), array([[2],
        [5],
        [8]])]

In [47]:
split(a,3,axis=0)

[array([[0, 1, 2]]), array([[3, 4, 5]]), array([[6, 7, 8]])]

In [48]:
b

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

In [49]:
b.ndim

2

In [50]:
b.size

9

In [51]:
b.shape

(3, 3)

In [52]:
b.itemsize

8

In [59]:
b=array([1+1j,complex(3,2)])
b

array([ 1.+1.j,  3.+2.j])

In [60]:
b.tolist()

[(1+1j), (3+2j)]

In [61]:
i2=np.eye(2)
print i2

[[ 1.  0.]
 [ 0.  1.]]


In [62]:
np.savetxt("eye.txt",i2)

In [16]:
c, v=np.loadtxt('/Users/fanchang/my_notebook/data.csv',
                delimiter=',', usecols=(6,7),unpack=True)
print c
print v

[ 336.1   339.32  345.03  344.32  343.44  346.5   351.88  355.2   358.16
  354.54  356.85  359.18  359.9   363.13  358.3   350.56  338.61  342.62
  342.88  348.16  353.21  349.31  352.12  359.56  360.    355.36  355.76
  352.47  346.67  351.99]
[ 21144800.  13473000.  15236800.   9242600.  14064100.  11494200.
  17322100.  13608500.  17240800.  33162400.  13127500.  11086200.
  10149000.  17184100.  18949000.  29144500.  31162200.  23994700.
  17853500.  13572000.  14395400.  16290300.  21521000.  17885200.
  16188000.  19504300.  12718000.  16192700.  18138800.  16824200.]


In [17]:
vwap=np.average(c,weights=v)
print ("VWAP =", vwap)

('VWAP =', 350.58954935320088)


In [18]:
np.dot(c,v)/np.sum(v)

350.58954935320088

In [19]:
np.sum(c*v)/np.sum(v)

350.58954935320088

In [20]:
h,l=np.loadtxt('/Users/fanchang/my_notebook/data.csv',
               delimiter=',', usecols=(4,5),unpack=True)
print h
print l

[ 344.4   340.04  345.65  345.25  344.24  346.7   353.25  355.52  359.
  360.    357.8   359.48  359.97  364.9   360.27  359.5   345.4   344.64
  345.15  348.43  355.05  355.72  354.35  359.79  360.29  361.67  357.4
  354.76  349.77  352.32]
[ 333.53  334.3   340.98  343.55  338.55  343.51  347.64  352.15  354.87
  348.    353.54  356.71  357.55  360.5   356.52  349.52  337.72  338.61
  338.37  344.8   351.12  347.68  348.4   355.92  357.75  351.31  352.25
  350.6   344.9   345.  ]


In [21]:
print np.max(h)
print np.min(l)

364.9
333.53


In [22]:
print np.ptp(h)
print np.ptp(l)

24.86
26.97


In [82]:
c=np.loadtxt('/Users/fanchang/Downloads/CODE/Chapter3/data.csv',
                delimiter=',', usecols=(6,),unpack=True)
print np.median(c)

352.055


In [84]:
print c
print np.sort(c)

[ 336.1   339.32  345.03  344.32  343.44  346.5   351.88  355.2   358.16
  354.54  356.85  359.18  359.9   363.13  358.3   350.56  338.61  342.62
  342.88  348.16  353.21  349.31  352.12  359.56  360.    355.36  355.76
  352.47  346.67  351.99]
[ 336.1   338.61  339.32  342.62  342.88  343.44  344.32  345.03  346.5
  346.67  348.16  349.31  350.56  351.88  351.99  352.12  352.47  353.21
  354.54  355.2   355.36  355.76  356.85  358.16  358.3   359.18  359.56
  359.9   360.    363.13]


In [87]:
print np.var(c)
print np.std(c)

50.1265178889
7.08000832548


In [89]:
returns = np.diff( c ) / c[ : -1]
print("Standard deviation =", np.std(returns))

('Standard deviation =', 0.012922134436826306)


In [90]:
np.diff( c )

array([  3.22,   5.71,  -0.71,  -0.88,   3.06,   5.38,   3.32,   2.96,
        -3.62,   2.31,   2.33,   0.72,   3.23,  -4.83,  -7.74, -11.95,
         4.01,   0.26,   5.28,   5.05,  -3.9 ,   2.81,   7.44,   0.44,
        -4.64,   0.4 ,  -3.29,  -5.8 ,   5.32])

In [91]:
c[ : -1]

array([ 336.1 ,  339.32,  345.03,  344.32,  343.44,  346.5 ,  351.88,
        355.2 ,  358.16,  354.54,  356.85,  359.18,  359.9 ,  363.13,
        358.3 ,  350.56,  338.61,  342.62,  342.88,  348.16,  353.21,
        349.31,  352.12,  359.56,  360.  ,  355.36,  355.76,  352.47,
        346.67])

In [12]:
c

336.10000000000002

In [93]:
returns

array([ 0.00958048,  0.01682777, -0.00205779, -0.00255576,  0.00890985,
        0.0155267 ,  0.00943503,  0.00833333, -0.01010721,  0.00651548,
        0.00652935,  0.00200457,  0.00897472, -0.01330102, -0.02160201,
       -0.03408832,  0.01184253,  0.00075886,  0.01539897,  0.01450483,
       -0.01104159,  0.00804443,  0.02112916,  0.00122372, -0.01288889,
        0.00112562, -0.00924781, -0.0164553 ,  0.01534601])

In [95]:
logreturns = np.diff( np.log(c) )
print logreturns

[ 0.00953488  0.01668775 -0.00205991 -0.00255903  0.00887039  0.01540739
  0.0093908   0.0082988  -0.01015864  0.00649435  0.00650813  0.00200256
  0.00893468 -0.01339027 -0.02183875 -0.03468287  0.01177296  0.00075857
  0.01528161  0.01440064 -0.011103    0.00801225  0.02090904  0.00122297
 -0.01297267  0.00112499 -0.00929083 -0.01659219  0.01522945]


In [96]:
returns

array([ 0.00958048,  0.01682777, -0.00205779, -0.00255576,  0.00890985,
        0.0155267 ,  0.00943503,  0.00833333, -0.01010721,  0.00651548,
        0.00652935,  0.00200457,  0.00897472, -0.01330102, -0.02160201,
       -0.03408832,  0.01184253,  0.00075886,  0.01539897,  0.01450483,
       -0.01104159,  0.00804443,  0.02112916,  0.00122372, -0.01288889,
        0.00112562, -0.00924781, -0.0164553 ,  0.01534601])

In [97]:
posretindices = np.where(returns > 0)
print posretindices

(array([ 0,  1,  4,  5,  6,  7,  9, 10, 11, 12, 16, 17, 18, 19, 21, 22, 23,
       25, 28]),)


In [101]:
returns[posretindices]

array([ 0.00958048,  0.01682777,  0.00890985,  0.0155267 ,  0.00943503,
        0.00833333,  0.00651548,  0.00652935,  0.00200457,  0.00897472,
        0.01184253,  0.00075886,  0.01539897,  0.01450483,  0.00804443,
        0.02112916,  0.00122372,  0.00112562,  0.01534601])

In [106]:
import datetime
def datestr2num(s):
    return datetime.datetime.strptime(s,"%d-%m-%Y").date().weekday()

dates, close=np.loadtxt('/Users/fanchang/Downloads/CODE/Chapter3/data.csv', 
                        delimiter=',',usecols=(1,6), 
                        converters={1: datestr2num},
                        unpack=True)

In [107]:
dates

array([ 4.,  0.,  1.,  2.,  3.,  4.,  0.,  1.,  2.,  3.,  4.,  0.,  1.,
        2.,  3.,  4.,  1.,  2.,  3.,  4.,  0.,  1.,  2.,  3.,  4.,  0.,
        1.,  2.,  3.,  4.])

In [108]:
np.take(close,0)

336.10000000000002

In [109]:
close

array([ 336.1 ,  339.32,  345.03,  344.32,  343.44,  346.5 ,  351.88,
        355.2 ,  358.16,  354.54,  356.85,  359.18,  359.9 ,  363.13,
        358.3 ,  350.56,  338.61,  342.62,  342.88,  348.16,  353.21,
        349.31,  352.12,  359.56,  360.  ,  355.36,  355.76,  352.47,
        346.67,  351.99])

In [111]:
dates

array([ 4.,  0.,  1.,  2.,  3.,  4.,  0.,  1.,  2.,  3.,  4.,  0.,  1.,
        2.,  3.,  4.,  1.,  2.,  3.,  4.,  0.,  1.,  2.,  3.,  4.,  0.,
        1.,  2.,  3.,  4.])

In [126]:
averages=np.zeros([5,])
for i in range(5):
    indices = np.where(dates == i)
    prices = np.take(close, indices)
    avg = np.mean(prices)
    print("Day", i, "prices", prices, "Average", avg)
    averages[i] = avg

('Day', 0, 'prices', array([[ 339.32,  351.88,  359.18,  353.21,  355.36]]), 'Average', 351.79000000000008)
('Day', 1, 'prices', array([[ 345.03,  355.2 ,  359.9 ,  338.61,  349.31,  355.76]]), 'Average', 350.63500000000005)
('Day', 2, 'prices', array([[ 344.32,  358.16,  363.13,  342.62,  352.12,  352.47]]), 'Average', 352.1366666666666)
('Day', 3, 'prices', array([[ 343.44,  354.54,  358.3 ,  342.88,  359.56,  346.67]]), 'Average', 350.89833333333331)
('Day', 4, 'prices', array([[ 336.1 ,  346.5 ,  356.85,  350.56,  348.16,  360.  ,  351.99]]), 'Average', 350.02285714285711)


In [115]:
indices = np.where(dates == 0)
print indices

(array([ 1,  6, 11, 20, 25]),)


In [124]:
np.array([dates[indices],close[indices]])

array([[   0.  ,    0.  ,    0.  ,    0.  ,    0.  ],
       [ 339.32,  351.88,  359.18,  353.21,  355.36]])

In [127]:
averages

array([ 351.79      ,  350.635     ,  352.13666667,  350.89833333,
        350.02285714])

In [128]:
np.arange('2015-04-22', '2015-05-22', 7, dtype='datetime64')

array(['2015-04-22', '2015-04-29', '2015-05-06', '2015-05-13', '2015-05-20'], dtype='datetime64[D]')

In [137]:
close[np.where(dates == 1)]

array([ 345.03,  355.2 ,  359.9 ,  338.61,  349.31,  355.76])

In [136]:
indices = np.where(dates == 0)
print indices

(array([ 1,  6, 11, 20, 25]),)


In [156]:
import datetime
def datestr2num(s):
    return datetime.datetime.strptime(s,"%d-%m-%Y").date().weekday()

def summarize(a, o, h, l, c):
    monday_open = o[a[0]]
    week_high = np.max( np.take(h, a) )
    week_low = np.min( np.take(l, a) )
    friday_close = c[a[-1]]
    return("APPL", monday_open, week_high, week_low, friday_close)

dates,opened,high,low,close=np.loadtxt('/Users/fanchang/Downloads/CODE/Chapter3/data.csv', 
                        delimiter=',',usecols=(1,3,4,5,6), 
                        converters={1: datestr2num},
                        unpack=True)
dates=dates[:16]
opened=opened[:16]
high=high[:16]
low=low[:16]
close=close[:16]

# get first Monday
first_monday = np.ravel(np.where(dates == 0))[0]
print("The first Monday index is", first_monday)
# get last Friday
last_friday = np.ravel(np.where(dates == 4))[-1]
print("The last Friday index is", last_friday)

weeks_indices = np.arange(first_monday, last_friday + 1)
print("Weeks indices initial", weeks_indices)

weeks_indices = np.split(weeks_indices, 3)
print("Weeks indices after split", weeks_indices)

weeksummary = np.apply_along_axis(summarize, 1, weeks_indices, 
                                  opened, high, low, close)

print("Week summary", weeksummary)

np.savetxt("weeksummary.csv", weeksummary, delimiter=",", fmt="%s")

('The first Monday index is', 1)
('The last Friday index is', 15)
('Weeks indices initial', array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15]))
('Weeks indices after split', [array([1, 2, 3, 4, 5]), array([ 6,  7,  8,  9, 10]), array([11, 12, 13, 14, 15])])
('Week summary', array([['APPL', '335.8', '346.7', '334.3', '346.5'],
       ['APPL', '347.8', '360.0', '347.6', '356.8'],
       ['APPL', '356.7', '364.9', '349.5', '350.5']], 
      dtype='|S5'))


In [151]:
import datetime
def datestr2num(s):
    return datetime.datetime.strptime(s,"%d-%m-%Y").date().weekday()

dates,opened,high,low,close=np.loadtxt('/Users/fanchang/Downloads/CODE/Chapter3/data.csv', 
                        delimiter=',',usecols=(1,3,4,5,6), 
                        converters={1: datestr2num},
                        unpack=True)
print dates,opened,high,low,close

[ 4.  0.  1.  2.  3.  4.  0.  1.  2.  3.  4.  0.  1.  2.  3.  4.  1.  2.
  3.  4.  0.  1.  2.  3.  4.  0.  1.  2.  3.  4.] [ 344.17  335.8   341.3   344.45  343.8   343.61  347.89  353.68  355.19
  357.39  354.75  356.79  359.19  360.8   357.1   358.21  342.05  338.77
  344.02  345.29  351.21  355.47  349.96  357.2   360.07  361.11  354.91
  354.69  349.69  345.4 ] [ 344.4   340.04  345.65  345.25  344.24  346.7   353.25  355.52  359.
  360.    357.8   359.48  359.97  364.9   360.27  359.5   345.4   344.64
  345.15  348.43  355.05  355.72  354.35  359.79  360.29  361.67  357.4
  354.76  349.77  352.32] [ 333.53  334.3   340.98  343.55  338.55  343.51  347.64  352.15  354.87
  348.    353.54  356.71  357.55  360.5   356.52  349.52  337.72  338.61
  338.37  344.8   351.12  347.68  348.4   355.92  357.75  351.31  352.25
  350.6   344.9   345.  ] [ 336.1   339.32  345.03  344.32  343.44  346.5   351.88  355.2   358.16
  354.54  356.85  359.18  359.9   363.13  358.3   350.56  338.61  342.62